"""
airports.py

Caribbean place-name -> IATA airport code lookup.

Shared by tools.py (destination/route lookups) and flight_service.py
(flight search) so both use the same normalization.
"""

PLACE_ALIASES = {
    "trinidad": "POS",
    "trinidad and tobago": "POS",
    "port of spain": "POS",
    "pos": "POS",
    "tobago": "TAB",
    "scarborough": "TAB",
    "tab": "TAB",
    "grenada": "GND",
    "gnd": "GND",
    "barbados": "BGI",
    "bgi": "BGI",
    "saint lucia": "SLU",
    "st lucia": "SLU",
    "st. lucia": "SLU",
    "slu": "SLU",
    "guyana": "GEO",
    "georgetown": "GEO",
    "geo": "GEO",
    "dominica": "DOM",
    "dom": "DOM",
    "antigua": "ANU",
    "antigua and barbuda": "ANU",
    "anu": "ANU",
    "jamaica": "KIN",
    "kingston": "KIN",
    "kin": "KIN",
    "bahamas": "NAS",
    "the bahamas": "NAS",
    "nassau": "NAS",
    "nas": "NAS",
    "cuba": "HAV",
    "havana": "HAV",
    "hav": "HAV",
    "dominican republic": "SDQ",
    "santo domingo": "SDQ",
    "sdq": "SDQ",
    "haiti": "PAP",
    "port-au-prince": "PAP",
    "pap": "PAP",
    "saint kitts and nevis": "SKB",
    "st kitts and nevis": "SKB",
    "skb": "SKB",
    "saint vincent and the grenadines": "SVD",
    "st vincent and the grenadines": "SVD",
    "svd": "SVD",
    "anguilla": "AXA",
    "axa": "AXA",
    "british virgin islands": "EIS",
    "eis": "EIS",
    "cayman islands": "GCM",
    "gcm": "GCM",
    "montserrat": "MNI",
    "mni": "MNI",
    "turks and caicos islands": "PLS",
    "turks and caicos": "PLS",
    "pls": "PLS",
    "guadeloupe": "PTP",
    "ptp": "PTP",
    "martinique": "FDF",
    "fdf": "FDF",
    "saint barthelemy": "SBH",
    "st barthelemy": "SBH",
    "st barths": "SBH",
    "sbh": "SBH",
    "saint martin": "SFG",
    "st martin": "SFG",
    "sfg": "SFG",
    "aruba": "AUA",
    "aua": "AUA",
    "curacao": "CUR",
    "curaçao": "CUR",
    "cur": "CUR",
    "sint maarten": "SXM",
    "sxm": "SXM",
    "bonaire": "BON",
    "bon": "BON",
    "sint eustatius": "EUX",
    "eux": "EUX",
    "saba": "SAB",
    "sab": "SAB",
    "puerto rico": "SJU",
    "san juan": "SJU",
    "sju": "SJU",
    "u.s. virgin islands": "STT",
    "us virgin islands": "STT",
    "united states virgin islands": "STT",
    "stt": "STT",
}


def normalize_place(place):
    """Turns common place names into airport codes when known."""
    cleaned = place.strip().lower()

    return PLACE_ALIASES.get(cleaned, place.strip().upper())
